use_gpu: true
model:
  name: timm/nf_resnet50.ra2_in1k
  num_classes: 6
  pretrained: true

trainer:
  epochs: 20
  lr: 1e-3
  max_lr: 1e-3
  print_every: 5
  total_step: 10*5*10000
  save_dir: ./

loss:
  name: focal

kfold: 
  use_kfold: true
  num_fold: 1

datasets:
  root: ../../Datasets/Classification/Data_classification/
  image_width: 224
  image_height: 224
  batch_size: 32
